'use strict';

require('./navbar');
require('./fontRenderer');
require('./fontHeader');
require('./fontCardTitlebar');
require('./fontCardsView');
require('./fontCardsTypeSwitcher');
require('./fontCardAdd');
require('./fontCardSimple');
require('./fontCardLetters');
require('./reviewCardSideBySide');
require('./reviewCardOpacitySelector');
require('./reviewCardOpacity');
require('./fontSelectorDropdown');
require('./filePickerButton');
require('./loadingSpinner');
require('./dottedPaginator');
require('./fontParametersMenu');
require('./colorPicker');
require('./fontMetadataEditor');
require('./googleFontsChooser');
require('./contenteditable');
require('./comparisonTypeSwitcher');
require('./fontsComparisonDropdown');
